linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - revive
    - gosec
    - gofmt
    - misspell
    - unconvert
    - bodyclose
    - noctx

linters-settings:
  revive:
    rules:
      - name: exported
        severity: warning
      - name: var-naming
        severity: warning
      - name: error-return
        severity: warning
      - name: error-strings
        severity: warning

  gosec:
    excludes:
      - G304
      - G306

  errcheck:
    check-type-assertions: false
    check-blank: false

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
    - path: \.pb\.go
      linters:
        - depguard
  max-issues-per-linter: 50
  max-same-issues: 10
